# Generated by Django 5.1.4 on 2025-01-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('storage', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('graphics', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('battrey', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('post_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
