# Generated by Django 5.1.4 on 2025-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_alter_laptoppost_battrey_alter_laptoppost_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptoppost',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AddField(
            model_name='laptoppost',
            name='channel_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptoppost',
            name='channel_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
