# Generated by Django 5.1.4 on 2025-01-15 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_alter_laptoppost_battrey_alter_laptoppost_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='similarityscore',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='similarityscore',
            name='item_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_scores_as_a', to='laptops.laptoppost'),
        ),
        migrations.AlterField(
            model_name='similarityscore',
            name='item_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_scores_as_b', to='laptops.laptoppost'),
        ),
        migrations.AddConstraint(
            model_name='similarityscore',
            constraint=models.UniqueConstraint(fields=('item_a', 'item_b'), name='unique_similarity_score'),
        ),
    ]
