# Generated by Django 5.1.4 on 2025-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_alter_similarityscore_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopimage',
            name='image',
            field=models.ImageField(unique=True, upload_to='telegram_assets/laptop_images/'),
        ),
    ]
