# Generated by Django 5.1.4 on 2025-08-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0004_alter_laptopimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('mention_text', models.TextField()),
                ('unread_count', models.PositiveIntegerField()),
                ('is_processed', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('marked_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='laptops.telegramchat')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('channel', 'message_id')},
            },
        ),
    ]
